name: ditonton
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  about:
    path: about
  core:
    path: core
  movie:
    path: movie
  tv_series:
    path: tv_series

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  google_fonts: ^2.1.0
  flutter_rating_bar: ^4.0.0
  cached_network_image: ^3.2.0
  get_it: ^7.2.0
  sqflite: ^2.0.2
  path_provider: ^2.0.2
  flutter_bloc: ^7.3.0
  rxdart: ^0.27.1
  encrypt: ^5.0.1
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^2.8.0
  mockito: ^5.0.8
  build_runner: ^2.0.4
  bloc_test: ^8.0.1
  flutter_lints: ^1.0.4
  test_cov_console: ^0.2.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/
